[General]

bypass-system = true

ipv6 = false
prefer-ipv6 = false

dns-server = https://1.1.1.1/dns-query#proxy
fallback-dns-server = https://1.1.1.1/dns-query#proxy

dns-fallback-system = false
dns-direct-system = false
dns-direct-fallback-proxy = false

udp-policy-not-supported-behaviour = REJECT


[Rule]

FINAL,PROXY
